/**
 * Build script: generates assets/dax-monarch.js (DAX Monarch grammar for Monaco).
 *
 * Original intent: fetch microsoft/powerbi-vscode syntaxes/dax.tmLanguage.json and
 * convert with tm-to-monarch. Both the GitHub path and the npm package (tm-to-monarch)
 * are unavailable (404 / not found on npm as of 2024-03), so the grammar is hand-crafted
 * below. Re-run this script whenever DAX syntax evolves.
 *
 * Usage: node scripts/build_dax_grammar.mjs
 */

import { writeFileSync } from "fs";
import { fileURLToPath } from "url";
import { dirname, resolve } from "path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const outPath = resolve(__dirname, "../assets/dax-monarch.js");

const keywords = [
  "EVALUATE","RETURN","VAR","DEFINE","MEASURE","COLUMN","TABLE",
  "CALCULATE","CALCULATETABLE","FILTER","ALL","ALLEXCEPT","ALLSELECTED",
  "ALLNOBLANKROW","REMOVEFILTERS","KEEPFILTERS","USERELATIONSHIP","CROSSFILTER",
  "RELATED","RELATEDTABLE","SUMMARIZE","SUMMARIZECOLUMNS","ADDCOLUMNS",
  "SELECTCOLUMNS","TOPN","RANKX","ROW","UNION","INTERSECT","EXCEPT",
  "NATURALINNERJOIN","NATURALLEFTOUTERJOIN","GENERATE","GENERATEALL","CROSSJOIN",
  "VALUES","DISTINCT","HASONEFILTER","HASONEVALUE","SELECTEDVALUE","ISINSCOPE",
  "IF","IFERROR","SWITCH","COALESCE","NOT","AND","OR","IN","TRUE","FALSE","BLANK",
  "ISBLANK","ISERROR","ISLOGICAL","ISNUMBER","ISTEXT","ISNONTEXT","ISFILTERED",
  "ISCROSSFILTERED","CONTAINSROW","CONTAINS",
  "SUM","SUMX","AVERAGE","AVERAGEX","MIN","MINX","MAX","MAXX","COUNT","COUNTA",
  "COUNTX","COUNTROWS","COUNTBLANK","DISTINCTCOUNT","DISTINCTCOUNTNOBLANK",
  "DIVIDE","ABS","CEILING","FLOOR","ROUND","ROUNDUP","ROUNDDOWN","TRUNC","INT",
  "MOD","POWER","SQRT","EXP","LOG","LOG10","LN","SIGN","RAND","RANDBETWEEN",
  "TODAY","NOW","DATE","TIME","YEAR","MONTH","DAY","HOUR","MINUTE","SECOND",
  "WEEKDAY","WEEKNUM","DATEDIFF","DATEADD","EDATE","EOMONTH","NETWORKDAYS",
  "CALENDARAUTO","CALENDAR","SAMEPERIODLASTYEAR","PARALLELPERIOD",
  "DATESINPERIOD","DATESBETWEEN","DATESMTD","DATESQTD","DATESYTD",
  "TOTALYTD","TOTALQTD","TOTALMTD","PREVIOUSDAY","PREVIOUSMONTH",
  "PREVIOUSQUARTER","PREVIOUSYEAR","NEXTDAY","NEXTMONTH","NEXTQUARTER","NEXTYEAR",
  "STARTOFMONTH","STARTOFQUARTER","STARTOFYEAR","ENDOFMONTH","ENDOFQUARTER","ENDOFYEAR",
  "FORMAT","CONCATENATE","CONCATENATEX","LEFT","RIGHT","MID","LEN","UPPER","LOWER",
  "TRIM","SUBSTITUTE","SEARCH","FIND","REPLACE","REPT","FIXED","TEXT","VALUE",
  "EXACT","LOOKUPVALUE","EARLIER","EARLIEST","PATH","PATHITEM",
  "PATHITEMREVERSE","PATHCONTAINS","PATHLENGTH","TREATAS",
  "GENERATESERIES","SEQUENCE","SAMPLE",
];

const grammar = {
  defaultToken: "",
  ignoreCase: true,
  tokenPostfix: ".dax",
  keywords,
  operators: ["=","<>","<","<=",">",">=","+","-","*","/","^","&","&&","||","!"],
  tokenizer: {
    root: [
      [/'[^']*'/, "string.table"],
      [/\[[^\]]*\]/, "variable.field"],
      [/"([^"\\]|\\.)*"/, "string"],
      [/--.*$/, "comment"],
      [/\/\*/, "comment", "@blockComment"],
      [/\b\d+(\.\d+)?\b/, "number"],
      [
        /[A-Za-z_]\w*/,
        { cases: { "@keywords": "keyword", "@default": "identifier" } },
      ],
      [/[=<>!&|+\-*\/^]+/, "operator"],
      [/[(),;]/, "delimiter"],
    ],
    blockComment: [
      [/[^/*]+/, "comment"],
      [/\*\//, "comment", "@pop"],
      [/[/*]/, "comment"],
    ],
  },
};

const banner = `// DAX Monarch tokenizer grammar for Monaco Editor.\n// Generated by scripts/build_dax_grammar.mjs — re-run to refresh.\n`;
const content = `${banner}window._daxMonarchTokens = ${JSON.stringify(grammar, null, 2)};\n`;

writeFileSync(outPath, content, "utf8");
console.log(`Written: ${outPath}`);
